# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"SSUDock": "00_core.ipynb",
         "temp_write": "00_core.ipynb",
         "molecule_identifier": "00_core.ipynb",
         "is_it_file": "00_core.ipynb",
         "clean": "00_core.ipynb",
         "main": "00_core.ipynb",
         "__date__": "00_core.ipynb",
         "__author__": "00_core.ipynb",
         "__version__": "00_core.ipynb",
         "console": "00_core.ipynb",
         "blue_console": "00_core.ipynb",
         "note_console": "00_core.ipynb",
         "clean_all": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://Takshan.github.io/ssudock/"

git_url = "https://github.com/Takshan/ssudock/tree/master/"

def custom_doc_links(name): return None
